name: Build

on:
  - push

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: '[BUILD] | Install Dependencies'
        run: npm install
        shell: bash

      - name: '[BUILD] | Build'
        run: npm run build
        shell: bash
