name: Publish Develop

on:
  - workflow_dispatch

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: '[INSTALL] | Install Dependencies'
        run: npm ci
        shell: bash

      - name: '[BUILD] | Build'
        run: npm run build
        shell: bash

      - name: '[ACTION] | Clone publish s3 action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/publish-s3-action
          ref: 5.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS }}
          path: ./publish-s3-action

      - name: '[ACTION] | Run publish s3 action'
        uses: './publish-s3-action/application/github'
        with:
          BUILD_FOLDER: build
          BUCKET_NAME: admin.senoritascc.com.br
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          AWS_ROLE_DURATION_SECONDS: 3600

      - name: '[ACTION] | Clone publish Cloudfront action'
        uses: actions/checkout@v3
        with:
          repository: heronlabs/publish-cloudfront-action
          ref: 1.0.0
          token: ${{ secrets.AUTHOR_PERSONAL_ACCESS}}
          path: ./publish-cloudfront-action

      - name: '[ACTION] | Run publish Cloudfront action'
        uses: './publish-cloudfront-action/application/github'
        with:
          DISTRIBUTION_ID: EIU0HEHX6R3JD
          AWS_REGION: ${{ secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME}}
          AWS_ROLE_DURATION_SECONDS: 3600
